"""
Pydantic models for the Business Intelligence Agent API boundaries.
Defines models for requests, responses, internal data models, and error responses.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """
    Request payload for the chat endpoint.
    """
    message: str = Field(..., description="The user's query or message.")
    conversation_id: Optional[str] = Field(None, description="The session or conversation ID to maintain history.")

class ChatResponse(BaseModel):
    """
    Response payload returned by the chat endpoint.
    """
    answer: str = Field(..., description="The conversational analyst response narration generated by the LLM.")
    conversation_id: str = Field(..., description="The session or conversation ID.")
    data_complete: bool = Field(..., description="True if no essential data was missing or dropped, otherwise False.")
    structured_summary: Optional[Dict[str, Any]] = Field(None, description="The cleaned and aggregated JSON analytics summary used by the LLM.")
    missing_data_notes: Optional[List[str]] = Field(None, description="Explicit notes detailing missing, malformed, or dropped fields.")

class LeadershipSummaryResponse(BaseModel):
    """
    Response payload returned by the leadership summary endpoint.
    """
    narrative: str = Field(..., description="The formatted weekly leadership narrative report generated by the LLM.")
    data_complete: bool = Field(..., description="True if no essential data was missing or dropped, otherwise False.")
    structured_summary: Optional[Dict[str, Any]] = Field(None, description="The comprehensive underlying analytics summary.")
    missing_data_notes: Optional[List[str]] = Field(None, description="Explicit notes detailing missing, malformed, or dropped fields.")

class DealItem(BaseModel):
    """
    Pydantic model representing a cleaned and normalized Deal.
    """
    id: str = Field(..., description="Unique identifier for the deal.")
    name: str = Field(..., description="Name of the deal.")
    sector: Optional[str] = Field(None, description="Industry sector (e.g., Mining, Infrastructure).")
    stage: Optional[str] = Field(None, description="Deal stage (e.g., Won, Lost, Lead).")
    value: Optional[float] = Field(0.0, description="Estimated deal value.")
    probability: Optional[float] = Field(0.0, description="Closure probability (0.0 to 1.0 or 0 to 100).")
    expected_close_date: Optional[str] = Field(None, description="Expected close date (YYYY-MM-DD).")
    owner: Optional[str] = Field(None, description="Owner of the deal.")

class WorkOrderItem(BaseModel):
    """
    Pydantic model representing a cleaned and normalized Work Order.
    """
    id: str = Field(..., description="Unique identifier for the work order.")
    name: str = Field(..., description="Name/title of the work order.")
    status: Optional[str] = Field(None, description="Work order status (e.g., Completed, In Progress, Delayed).")
    start_date: Optional[str] = Field(None, description="Start date (YYYY-MM-DD).")
    due_date: Optional[str] = Field(None, description="Due date/deadline (YYYY-MM-DD).")
    sector: Optional[str] = Field(None, description="Industry sector (e.g., Mining, Infrastructure).")
    assigned_to: Optional[str] = Field(None, description="Assigned delivery lead or team member.")

class BoardData(BaseModel):
    """
    Container representing the state of both deals and work orders.
    """
    deals: List[DealItem] = Field(default_factory=list, description="List of cleaned deals.")
    work_orders: List[WorkOrderItem] = Field(default_factory=list, description="List of cleaned work orders.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Operational metadata like fetch timestamp, cache status, raw vs cleaned counts.")

class ErrorResponse(BaseModel):
    """
    Pydantic model returned on API failures.
    """
    detail: str = Field(..., description="A friendly, specific error message explaining what failed.")
    error_type: str = Field(..., description="The category of the error (e.g., MondayAPIError, OpenAIError, ValidationException).")
